In [2]:
with open("the-verdict.txt", 'r', encoding="utf-8") as f:
    raw_text = f.read()

print(f"total no of characters: {len(raw_text)}")

total no of characters: 20479


In [3]:
print(raw_text[:99])      

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [4]:
import re

In [5]:
text = "Wow! NLP, AI & ML: they're all amazing; aren't they? Let's split - and see: how it works."

pattern = r'([,.:;?_!&"\(\)\'|\-]\s)'

result = re.split(pattern, text)

result = [item.strip() for item in result if item.strip()]
print(result)

['Wow', '!', 'NLP', ',', 'AI', '&', 'ML', ':', "they're all amazing", ';', "aren't they", '?', "Let's split", '-', 'and see', ':', 'how it works.']


In [6]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(preprocessed[:30])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


**Step 1 – `re.split(...)`**

**Pattern**:
`([,.:;?_!"()\']|--|\s)`

* `[...]` → match any **one** punctuation character inside the brackets
* `--` → match a **double dash**
* `\s` → match **whitespace** (space, tab, newline)
* **Parentheses** `( ... )` → capture group, so the matched delimiters are also returned in the list

**Applied on**: `"Hello, world!  This is NLP--fun."`

The split keeps delimiters as separate list items:

```
[
    'Hello', ',', ' ', 'world', '!', ' ', ' ', 'This', ' ', 
    'is', ' ', 'NLP', '--', 'fun', '.', ''
]
```
**Step 2 – The for loop (list comprehension)**

```python
[item.strip() for item in preprocessed if item.strip()]
```

This is **equivalent** to:

```python
result = []
for item in preprocessed:
    if item.strip():              # Remove leading/trailing spaces, check if not empty
        result.append(item.strip())  # Add stripped version to result
```


**Dry Run of Loop**

**Initial**:
`result = []`

| `item`    | `item.strip()` | Non-empty? | Action           |
| --------- | -------------- | ---------- | ---------------- |
| `'Hello'` | `'Hello'`      | Yes        | Append `'Hello'` |
| `','`     | `','`          | Yes        | Append `','`     |
| `' '`     | `''`           | No         | Skip             |
| `'world'` | `'world'`      | Yes        | Append `'world'` |
| `'!'`     | `'!'`          | Yes        | Append `'!'`     |
| `' '`     | `''`           | No         | Skip             |
| `' '`     | `''`           | No         | Skip             |
| `'This'`  | `'This'`       | Yes        | Append `'This'`  |
| `' '`     | `''`           | No         | Skip             |
| `'is'`    | `'is'`         | Yes        | Append `'is'`    |
| `' '`     | `''`           | No         | Skip             |
| `'NLP'`   | `'NLP'`        | Yes        | Append `'NLP'`   |
| `'--'`    | `'--'`         | Yes        | Append `'--'`    |
| `'fun'`   | `'fun'`        | Yes        | Append `'fun'`   |
| `'.'`     | `'.'`          | Yes        | Append `'.'`     |
| `''`      | `''`           | No         | Skip             |



**Final `preprocessed` after loop**:

```
['Hello', ',', 'world', '!', 'This', 'is', 'NLP', '--', 'fun', '.']
```



In [7]:
len(preprocessed)

4690

In [8]:
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)

In [9]:
vocab_size

1130

In [10]:
type(all_words)

list

In [11]:
vocab = { token:integer for integer, token in enumerate(all_words)}

In [12]:
vocab.items()

dict_items([('!', 0), ('"', 1), ("'", 2), ('(', 3), (')', 4), (',', 5), ('--', 6), ('.', 7), (':', 8), (';', 9), ('?', 10), ('A', 11), ('Ah', 12), ('Among', 13), ('And', 14), ('Are', 15), ('Arrt', 16), ('As', 17), ('At', 18), ('Be', 19), ('Begin', 20), ('Burlington', 21), ('But', 22), ('By', 23), ('Carlo', 24), ('Chicago', 25), ('Claude', 26), ('Come', 27), ('Croft', 28), ('Destroyed', 29), ('Devonshire', 30), ('Don', 31), ('Dubarry', 32), ('Emperors', 33), ('Florence', 34), ('For', 35), ('Gallery', 36), ('Gideon', 37), ('Gisburn', 38), ('Gisburns', 39), ('Grafton', 40), ('Greek', 41), ('Grindle', 42), ('Grindles', 43), ('HAD', 44), ('Had', 45), ('Hang', 46), ('Has', 47), ('He', 48), ('Her', 49), ('Hermia', 50), ('His', 51), ('How', 52), ('I', 53), ('If', 54), ('In', 55), ('It', 56), ('Jack', 57), ('Jove', 58), ('Just', 59), ('Lord', 60), ('Made', 61), ('Miss', 62), ('Money', 63), ('Monte', 64), ('Moon-dancers', 65), ('Mr', 66), ('Mrs', 67), ('My', 68), ('Never', 69), ('No', 70), ('Now

In [13]:
vocab.keys()

dict_keys(['!', '"', "'", '(', ')', ',', '--', '.', ':', ';', '?', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be', 'Begin', 'Burlington', 'But', 'By', 'Carlo', 'Chicago', 'Claude', 'Come', 'Croft', 'Destroyed', 'Devonshire', 'Don', 'Dubarry', 'Emperors', 'Florence', 'For', 'Gallery', 'Gideon', 'Gisburn', 'Gisburns', 'Grafton', 'Greek', 'Grindle', 'Grindles', 'HAD', 'Had', 'Hang', 'Has', 'He', 'Her', 'Hermia', 'His', 'How', 'I', 'If', 'In', 'It', 'Jack', 'Jove', 'Just', 'Lord', 'Made', 'Miss', 'Money', 'Monte', 'Moon-dancers', 'Mr', 'Mrs', 'My', 'Never', 'No', 'Now', 'Nutley', 'Of', 'Oh', 'On', 'Once', 'Only', 'Or', 'Perhaps', 'Poor', 'Professional', 'Renaissance', 'Rickham', 'Riviera', 'Rome', 'Russian', 'Sevres', 'She', 'Stroud', 'Strouds', 'Suddenly', 'That', 'The', 'Then', 'There', 'They', 'This', 'Those', 'Though', 'Thwing', 'Thwings', 'To', 'Usually', 'Venetian', 'Victor', 'Was', 'We', 'Well', 'What', 'When', 'Why', 'Yes', 'You', '_', 'a', 'abdication', 'able', 'about'

In [14]:
vocab.values()

dict_values([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 21

In [15]:
for i, item in enumerate(vocab.items()):
    print(item)
    if i>50:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)
('His', 51)


In [16]:
import random

for item in random.sample(list(vocab.items()), 50):
    print(item)


('window-curtains', 1106)
('afterward', 139)
('azaleas', 190)
('beauty', 203)
('distinguished', 352)
('able', 117)
('.', 7)
('made', 654)
('consummate', 287)
('shaking', 874)
('packed', 743)
('balance', 193)
('suspected', 964)
('fullest', 479)
('own', 742)
('toward', 1024)
('years', 1123)
('glory', 496)
('dress-closets', 368)
('borne', 224)
('demand', 324)
('anywhere', 163)
('again', 140)
('abruptly', 120)
('heart', 537)
('whenever', 1091)
('twirling', 1041)
('curiosity', 306)
('poor', 781)
('bronzes', 233)
('Miss', 62)
('has', 529)
('three', 1004)
('attack', 183)
('seemed', 863)
('wish', 1107)
('here', 540)
('started', 924)
('complex', 282)
('managed', 658)
('trace', 1025)
('corner', 290)
('kind', 593)
('faith', 425)
('wants', 1076)
('previous', 791)
('s', 850)
('buying', 240)
('forgive', 462)
('grayish', 507)


In [17]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    
    def decode(self, ids):
        # Map IDs to Tokens and Join with Spaces
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text


- **Clean Up Spaces Before Punctuation**
```python
text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
```

- **Input**: 
  ```python
  text = "\" It 's the last he painted , you know , \" Mrs. Gisburn said with pardonable pride ."
  ```

- **Regular Expression Explanation**:
  - The pattern `\s+([,.?!"()\'])` matches:
    - `\s+`: One or more whitespace characters (spaces, tabs, etc.).
    - `([,.?!"()\'])`: A capturing group matching any single character from the set: `,`, `.`, `?`, `!`, `"`, `(`, `)`, `'`.
  - The replacement `\1` keeps the matched punctuation (the captured group) and removes the preceding whitespace.
  - This ensures punctuation like commas and periods are not preceded by spaces, making the text look natural.



In [18]:
tokenizer = SimpleTokenizerV1(vocab)

text = """
"It's the last he painted, you know," 
Mrs. Gisburn said with pardonable pride.
"""
ids = tokenizer.encode(text)
print(ids)

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


In [19]:
tokenizer.decode(ids)

'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

In [20]:
text="Hello, do you like tea?"
print(tokenizer.encode(text))

KeyError: 'Hello'

<div class="alert alert-success">

To deal with token which not present in vocabulary add 

Special context tokens to the vocab or to the gvien token

1. <code> <|unk|> </code>
2. <code> <|endoftext|> </code>

</div>

In [21]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token : integer for integer, token in enumerate(all_tokens)}

len(vocab)

1132

In [22]:
class SimpleTokenizerV2:

    def __init__(self, vocab):

        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [ item.strip() for item in preprocessed if item.strip() ]
        preprocessed = [ item if item in self.str_to_int else "<|unk|>" for item in preprocessed ]
        ids = [ self.str_to_int[s] for s in preprocessed]

        return ids
    

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [ ]:
# def encode(self, text):
#     preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
#     preprocessed = [item.strip() for item in preprocessed if item.strip()]
    
#     processed_tokens = []
#     for item in preprocessed:
#         if item in self.str_to_int:
#             processed_tokens.append(item)
#         else:
#             processed_tokens.append("<|unk|>")
    
#     ids = [self.str_to_int[s] for s in processed_tokens]
#     return ids


In [ ]:
tokenizer = SimpleTokenizerV2(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <endoftext> ".join((text1, text2))

print(text)

Hello, do you like tea? <endoftext> In the sunlit terraces of the palace.


In [ ]:
tokenizer.encode(text)

[1131, 5, 355, 1126, 628, 975, 10, 1131, 55, 988, 956, 984, 722, 988, 1131, 7]

In [ ]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>, do you like tea? <|unk|> In the sunlit terraces of the <|unk|>.'

<div class="alert alert-success">
Byte Pair Encoding

<div>

In [ ]:
! uv pip install tiktoken

Using Python 3.10.9 environment at: D:\pytorch\env1
Audited 1 package in 17ms


In [ ]:
import tiktoken

In [ ]:
tokenizer = tiktoken.get_encoding("gpt2")


In [ ]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)


integers = tokenizer.encode(text, allowed_special={'<|endoftext|>'})

print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


In [ ]:
strings = tokenizer.decode(integers)
print(strings)

Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


In [ ]:
integers = tokenizer.encode("Akwirw ier")
print(integers)

strings = tokenizer.decode(integers)
print(strings)

[33901, 86, 343, 86, 220, 959]
Akwirw ier


In [ ]:
import tiktoken

encodings = {
    "gpt2": tiktoken.get_encoding("gpt2"),
    "gpt3": tiktoken.get_encoding("p50k_base"),
    "gpt4": tiktoken.get_encoding("cl100k_base"),
}

vocab_size = {model: encoding.n_vocab for model, encoding in encodings.items()}

for model, size in vocab_size.items():
    print(f"The vocabulary size for {model.upper()} is: {size}")

The vocabulary size for GPT2 is: 50257
The vocabulary size for GPT3 is: 50281
The vocabulary size for GPT4 is: 100277


**Creating Input-Output Target Pairs**

In [ ]:
import tiktoken

with open("the-verdict.txt", "r") as f:
    raw_text = f.read()

tokenizer = tiktoken.get_encoding("gpt2")
enc_text = tokenizer.encode(raw_text)

In [ ]:
len(enc_text)

5145

In [ ]:
context_size = 4
enc_sample = enc_text[50:]

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y:    {y}")

x: [290, 4920, 2241, 287]
y:    [4920, 2241, 287, 257]


In [ ]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(context, "---->", desired)

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257


In [ ]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

 and ---->  established
 and established ---->  himself
 and established himself ---->  in
 and established himself in ---->  a


In [ ]:
import torch
# Make sure there is no file named 'torch.py' in your working directory.

In [ ]:
from torch.utils.data import Dataset, DataLoader

class GPTDataset1(Dataset):

    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use the sliding windwos to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids)-max_length, stride):
            input_chunk = token_ids[i:i+max_length]
            target_chunk = token_ids[i+1:i+max_length+1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)
    
    def __getitem__(self, index):
        return self.input_ids[index], self.target_ids[index]
    



**Step 1 – Initialization**

You call something like:

```python
dataset = GPTDataset1(txt, tokenizer, max_length=6, stride=3)
```

Parameters:

* `txt` → Your raw text string (the entire file content).
* `tokenizer` → Tokenizes the text into token IDs.
* `max_length` → Length of each training sequence.
* `stride` → Step size to move the sliding window.



**Step 2 – Tokenization**

```python
token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
```

* Converts the **entire text** into a list of integers.
  Example:
  If `txt = "Hello world"` and tokenizer maps:

```
"Hello" → 15496  
"world" → 995  
```

Then:

```python
token_ids = [15496, 995]
```


**Step 3 – Sliding Window Loop**

```python
for i in range(0, len(token_ids)-max_length, stride):
```

* Moves through `token_ids` with a **window size** of `max_length` and **step size** of `stride`.
* `len(token_ids) - max_length` ensures we don’t go out of range.

Example:
If:

```python
token_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9]
max_length = 6
stride = 3
```

The loop runs with:

```
i = 0 → window covers [1, 2, 3, 4, 5, 6]
i = 3 → window covers [4, 5, 6, 7, 8, 9]
```


**Step 4 – Creating Input & Target Chunks**

Inside the loop:

```python
input_chunk = token_ids[i : i+max_length]
target_chunk = token_ids[i+1 : i+max_length+1]
```

* `input_chunk` → The tokens fed **to the model**.
* `target_chunk` → The **shifted-by-one** tokens that the model should **predict**.

Example for `i = 0`:

```
input_chunk  = [1, 2, 3, 4, 5, 6]
target_chunk = [2, 3, 4, 5, 6, 7]
```


**Step 5 – Store as Tensors**

```python
self.input_ids.append(torch.tensor(input_chunk))
self.target_ids.append(torch.tensor(target_chunk))
```

* Stores each chunk as a **PyTorch tensor** for training.


**Step 6 – Dataset Behavior**

* `__len__()` → Returns **number of chunks** created.
* `__getitem__(index)` → Returns `(input_ids[index], target_ids[index])`.

Example:

```python
len(dataset)  →  number of sliding windows
dataset[0]    →  (tensor([1, 2, 3, 4, 5, 6]),
                  tensor([2, 3, 4, 5, 6, 7]))
```



In [ ]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True, num_workers=0):
    
    tokenizer = tiktoken.get_encoding("gpt2")

    dataset = GPTDataset1(txt, tokenizer, max_length, stride)

    dataloader = DataLoader(
        dataset, 
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader


In [ ]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)

print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [ ]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [ ]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
inputs, taget = next(data_iter)

print(f"Inputs:\n {inputs}")
print(f"Targets:\n {taget}")

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [  367,  2885,  1464,  1807],
        [ 2885,  1464,  1807,  3619],
        [ 1464,  1807,  3619,   402],
        [ 1807,  3619,   402,   271],
        [ 3619,   402,   271, 10899],
        [  402,   271, 10899,  2138],
        [  271, 10899,  2138,   257]])
Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 2885,  1464,  1807,  3619],
        [ 1464,  1807,  3619,   402],
        [ 1807,  3619,   402,   271],
        [ 3619,   402,   271, 10899],
        [  402,   271, 10899,  2138],
        [  271, 10899,  2138,   257],
        [10899,  2138,   257,  7026]])


In [ ]:
input_ids = torch.tensor([2, 3, 5, 1])


In [ ]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)

embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [ ]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [ ]:
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [ ]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, 
    batch_size=8, 
    max_length=max_length,
    stride=max_length,
    shuffle=False
)


data_iter = iter(dataloader)
inputs, tagets = next(data_iter)

print(f"Token IDs:\n {inputs}")
print(f"Inputs Shapes:\n {inputs.shape}")

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Inputs Shapes:
 torch.Size([8, 4])


In [ ]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


#### **Absolute Positional Embeddings**

In [ ]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [ ]:
pos_embeddings = pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)
print(pos_embeddings)

torch.Size([4, 256])
tensor([[-0.6486,  0.6104, -1.3630,  ...,  0.5562,  0.3620,  0.7280],
        [-1.1202,  0.9267,  0.0733,  ...,  0.2828,  1.3301,  0.6929],
        [ 0.6616,  0.0863, -0.3309,  ...,  0.0087,  0.9789,  0.4809],
        [-1.3929,  1.0655, -0.3036,  ..., -0.2142,  0.0666,  0.2834]],
       grad_fn=<EmbeddingBackward0>)


In [ ]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])
