In [1]:
import torch

In [33]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)


In [34]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [35]:
torch.manual_seed(123)

W_query = torch.nn.Parameter(torch.rand(d_in,d_out), requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in,d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in,d_out), requires_grad=False)

In [36]:
W_query

Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])

In [37]:
W_key

Parameter containing:
tensor([[0.1366, 0.1025],
        [0.1841, 0.7264],
        [0.3153, 0.6871]])

In [38]:
W_value

Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]])

In [39]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value

In [40]:
print(query_2) # query vector for 

tensor([0.4306, 1.4551])


In [41]:
keys = inputs @ W_key
values = inputs @ W_value
queries = inputs @ W_query

keys.shape

torch.Size([6, 2])

In [42]:
keys_2 = keys[1]
attn_scores_22 = query_2.dot(keys_2)
attn_scores_22

tensor(1.8524)

In [43]:
attn_scores_2 = query_2 @ keys.T # All attention scores for given query
print(attn_scores_2)

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])


In [44]:
# import torch

inputs = torch.tensor(
    [[0.43, 0.15, 0.89],  # Your     (x^1)
     [0.55, 0.87, 0.66],  # journey  (x^2)
     [0.57, 0.85, 0.64],  # starts   (x^3)
     [0.22, 0.58, 0.33],  # with     (x^4)
     [0.77, 0.25, 0.10],  # one      (x^5)
     [0.05, 0.80, 0.55]]  # step     (x^6)
)
# Structured Dry Run:
# 1. Initialize inputs: tensor([[0.43, 0.15, 0.89], [0.55, 0.87, 0.66], [0.57, 0.85, 0.64], [0.22, 0.58, 0.33], [0.77, 0.25, 0.10], [0.05, 0.80, 0.55]])
#    Shape: (6, 3)

x_2 = inputs[1]
# 2. x_2 = inputs[1] = tensor([0.55, 0.87, 0.66])  # journey

d_in = inputs.shape[1]
# 3. d_in = inputs.shape[1] = 3

d_out = 2
# 4. d_out = 2

torch.manual_seed(123)
# 5. Set random seed to 123 for reproducibility

W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
# 6. W_query = torch.rand(3, 2) with seed 123:
#    tensor([[0.2961, 0.5166],
#            [0.2516, 0.6886],
#            [0.0740, 0.8665]])
#    Shape: (3, 2)

W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
# 7. W_key = torch.rand(3, 2) with seed 123 (next random values):
#    tensor([[0.1366, 0.8220],
#            [0.2072, 0.3334],
#            [0.3454, 0.7662]])
#    Shape: (3, 2)

W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
# 8. W_value = torch.rand(3, 2) with seed 123 (next random values):
#    tensor([[0.1067, 0.7334],
#            [0.4304, 0.0919],
#            [0.2976, 0.3456]])
#    Shape: (3, 2)

queries = inputs @ W_query
# 9. queries = inputs @ W_query (6x3 @ 3x2 = 6x2):
#    - Row 0: [0.43*0.2961 + 0.15*0.2516 + 0.89*0.0740, 0.43*0.5166 + 0.15*0.6886 + 0.89*0.8665] = [0.2311, 1.0971]
#    - Row 1: [0.55*0.2961 + 0.87*0.2516 + 0.66*0.0740, 0.55*0.5166 + 0.87*0.6886 + 0.66*0.8665] = [0.4306, 1.4558]
#    - Row 2: [0.57*0.2961 + 0.85*0.2516 + 0.64*0.0740, 0.57*0.5166 + 0.85*0.6886 + 0.64*0.8665] = [0.4297, 1.4342]
#    - Row 3: [0.22*0.2961 + 0.58*0.2516 + 0.33*0.0740, 0.22*0.5166 + 0.58*0.6886 + 0.33*0.8665] = [0.2357, 0.7992]
#    - Row 4: [0.77*0.2961 + 0.25*0.2516 + 0.10*0.0740, 0.77*0.5166 + 0.25*0.6886 + 0.10*0.8665] = [0.2983, 0.6567]
#    - Row 5: [0.05*0.2961 + 0.80*0.2516 + 0.55*0.0740, 0.05*0.5166 + 0.80*0.6886 + 0.55*0.8665] = [0.2569, 1.0530]

#    queries = tensor([[0.2311, 1.0971],
#                     [0.4306, 1.4558],
#                     [0.4297, 1.4342],
#                     [0.2357, 0.7992],
#                     [0.2983, 0.6567],
#                     [0.2569, 1.0530]])
#    Shape: (6, 2)

keys = inputs @ W_key
# 10. keys = inputs @ W_key (6x3 @ 3x2 = 6x2):
#     - Row 0: [0.43*0.1366 + 0.15*0.2072 + 0.89*0.3454, 0.43*0.8220 + 0.15*0.3334 + 0.89*0.7662] = [0.3963, 1.0853]
#     - Row 1: [0.55*0.1366 + 0.87*0.2072 + 0.66*0.3454, 0.55*0.8220 + 0.87*0.3334 + 0.66*0.7662] = [0.4838, 1.2477]
#     - Row 2: [0.57*0.1366 + 0.85*0.2072 + 0.64*0.3454, 0.57*0.8220 + 0.85*0.3334 + 0.64*0.7662] = [0.4758, 1.2397]
#     - Row 3: [0.22*0.1366 + 0.58*0.2072 + 0.33*0.3454, 0.22*0.8220 + 0.58*0.3334 + 0.33*0.7662] = [0.2640, 0.6263]
#     - Row 4: [0.77*0.1366 + 0.25*0.2072 + 0.10*0.3454, 0.77*0.8220 + 0.25*0.3334 + 0.10*0.7662] = [0.1917, 0.7926]
#     - Row 5: [0.05*0.1366 + 0.80*0.2072 + 0.55*0.3454, 0.05*0.8220 + 0.80*0.3334 + 0.55*0.7662] = [0.3626, 0.7292]

#     keys = tensor([[0.3963, 1.0853],
#                    [0.4838, 1.2477],
#                    [0.4758, 1.2397],
#                    [0.2640, 0.6263],
#                    [0.1917, 0.7926],
#                    [0.3626, 0.7292]])
#     Shape: (6, 2)

values = inputs @ W_value
# 11. values = inputs @ W_value (6x3 @ 3x2 = 6x2):
#     - Row 0: [0.43*0.1067 + 0.15*0.4304 + 0.89*0.2976, 0.43*0.7334 + 0.15*0.0919 + 0.89*0.3456] = [0.3748, 0.6362]
#     - Row 1: [0.55*0.1067 + 0.87*0.4304 + 0.66*0.2976, 0.55*0.7334 + 0.87*0.0919 + 0.66*0.3456] = [0.6294, 0.7115]
#     - Row 2: [0.57*0.1067 + 0.85*0.4304 + 0.64*0.2976, 0.57*0.7334 + 0.85*0.0919 + 0.64*0.3456] = [0.6175, 0.7163]
#     - Row 3: [0.22*0.1067 + 0.58*0.4304 + 0.33*0.2976, 0.22*0.7334 + 0.58*0.0919 + 0.33*0.3456] = [0.3724, 0.3282]
#     - Row 4: [0.77*0.1067 + 0.25*0.4304 + 0.10*0.2976, 0.77*0.7334 + 0.25*0.0919 + 0.10*0.3456] = [0.2195, 0.6221]
#     - Row 5: [0.05*0.1067 + 0.80*0.4304 + 0.55*0.2976, 0.05*0.7334 + 0.80*0.0919 + 0.55*0.3456] = [0.5133, 0.3004]
#     values = tensor([[0.3748, 0.6362],
#                     [0.6294, 0.7115],
#                     [0.6175, 0.7163],
#                     [0.3724, 0.3282],
#                     [0.2195, 0.6221],
#                     [0.5133, 0.3004]])
#     Shape: (6, 2)

keys.shape
# 12. keys.shape = (6, 2)

keys_2 = keys[1]
# 13. keys_2 = keys[1] = tensor([0.4838, 1.2477])

# Note: `queries_2 = queries[1]`
queries_2 = queries[1]
# 14. queries_2 = queries[1] = tensor([0.4306, 1.4558])

attn_scores_22 = queries_2.dot(keys_2)
# 15. attn_scores_22 = queries_2.dot(keys_2) = 0.4306*0.4838 + 1.4558*1.2477 = 0.2084 + 1.8165 = 2.0249

print(attn_scores_22)
# 16. Print: tensor(2.0249)

# Structured Dry Run Summary:
# 1. Initialize inputs: tensor([[0.43, 0.15, 0.89], [0.55, 0.87, 0.66], [0.57, 0.85, 0.64], [0.22, 0.58, 0.33], [0.77, 0.25, 0.10], [0.05, 0.80, 0.55]])
# 2. x_2 = inputs[1] = tensor([0.55, 0.87, 0.66])
# 3. d_in = inputs.shape[1] = 3
# 4. d_out = 2
# 5. Set random seed: 123
# 6. W_query = tensor([[0.2961, 0.5166], [0.2516, 0.6886], [0.0740, 0.8665]])
# 7. W_key = tensor([[0.1366, 0.8220], [0.2072, 0.3334], [0.3454, 0.7662]])
# 8. W_value = tensor([[0.1067, 0.7334], [0.4304, 0.0919], [0.2976, 0.3456]])
# 9. queries = inputs @ W_query = tensor([[0.2311, 1.0971], [0.4306, 1.4558], [0.4297, 1.4342], [0.2357, 0.7992], [0.2983, 0.6567], [0.2569, 1.0530]])
# 10. keys = inputs @ W_key = tensor([[0.3963, 1.0853], [0.4838, 1.2477], [0.4758, 1.2397], [0.2640, 0.6263], [0.1917, 0.7926], [0.3626, 0.7292]])
# 11. values = inputs @ W_value = tensor([[0.3748, 0.6362], [0.6294, 0.7115], [0.6175, 0.7163], [0.3724, 0.3282], [0.2195, 0.6221], [0.5133, 0.3004]])
# 12. keys.shape = (6, 2)
# 13. keys_2 = keys[1] = tensor([0.4838, 1.2477])
# 14. queries_2 = queries[1] = tensor([0.4306, 1.4558])  # Assuming typo correction from query_2
# 15. attn_scores_22 = queries_2.dot(keys_2) = 0.4306*0.4838 + 1.4558*1.2477 = 2.0249
# 16. Print: tensor(2.0249)

tensor(1.8524)


In [45]:


# Assume inputs, queries, and keys from previous code
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],  # Your     (x^1)
     [0.55, 0.87, 0.66],  # journey  (x^2)
     [0.57, 0.85, 0.64],  # starts   (x^3)
     [0.22, 0.58, 0.33],  # with     (x^4)
     [0.77, 0.25, 0.10],  # one      (x^5)
     [0.05, 0.80, 0.55]]  # step     (x^6)
)
queries = torch.tensor(
    [[0.2311, 1.0971],
     [0.4306, 1.4558],
     [0.4297, 1.4342],
     [0.2357, 0.7992],
     [0.2983, 0.6567],
     [0.2569, 1.0530]]
)
keys = torch.tensor(
    [[0.3963, 1.0853],
     [0.4838, 1.2477],
     [0.4758, 1.2397],
     [0.2640, 0.6263],
     [0.1917, 0.7926],
     [0.3626, 0.7292]]
)

attn_scores = queries @ keys.T
attn_scores.shape
# 4. attn_scores.shape = (6, 6)
print(attn_scores)

# Structured Dry Run:
# 1. Input: queries = tensor([[0.2311, 1.0971], [0.4306, 1.4558], [0.4297, 1.4342], [0.2357, 0.7992], [0.2983, 0.6567], [0.2569, 1.0530]])
#           keys = tensor([[0.3963, 1.0853], [0.4838, 1.2477], [0.4758, 1.2397], [0.2640, 0.6263], [0.1917, 0.7926], [0.3626, 0.7292]])
# 2. Compute keys.T: tensor([[0.3963, 0.4838, 0.4758, 0.2640, 0.1917, 0.3626],
#                           [1.0853, 1.2477, 1.2397, 0.6263, 0.7926, 0.7292]])
# 3. Compute attn_scores = queries @ keys.T (6x2 @ 2x6 = 6x6):
#    - Row 0 (Your):   [1.2825, 1.4809, 1.4704, 0.7478, 0.9136, 0.8836]
#    - Row 1 (journey): [1.7507, 2.0249, 2.0098, 1.0250, 1.2368, 1.2177]
#    - Row 2 (starts):  [1.7269, 1.9966, 1.9817, 1.0113, 1.2187, 1.2015]
#    - Row 3 (with):    [0.5938, 1.1114, 1.1028, 0.5625, 0.6786, 0.6681]
#    - Row 4 (one):     [0.5294, 0.9639, 0.9560, 0.4898, 0.5778, 0.5868]
#    - Row 5 (step):    [1.2447, 1.4388, 1.4287, 0.7274, 0.8839, 0.8610]
# 4. attn_scores.shape = (6, 6)
# 5. Print: tensor([[1.2825, 1.4809, 1.4704, 0.7478, 0.9136, 0.8836],
#                  [1.7507, 2.0249, 2.0098, 1.0250, 1.2368, 1.2177],
#                  [1.7269, 1.9966, 1.9817, 1.0113, 1.2187, 1.2015],
#                  [0.5938, 1.1114, 1.1028, 0.5625, 0.6786, 0.6681],
#                  [0.5294, 0.9639, 0.9560, 0.4898, 0.5778, 0.5868],
#                  [1.2447, 1.4388, 1.4287, 0.7274, 0.8839, 0.8610]])

tensor([[1.2823, 1.4807, 1.4700, 0.7481, 0.9139, 0.8838],
        [1.7506, 2.0247, 2.0096, 1.0254, 1.2364, 1.2177],
        [1.7268, 1.9973, 1.9824, 1.0117, 1.2191, 1.2016],
        [0.9608, 1.1112, 1.1029, 0.5628, 0.6786, 0.6682],
        [0.8309, 0.9637, 0.9560, 0.4900, 0.5777, 0.5870],
        [1.2446, 1.4381, 1.4276, 0.7273, 0.8839, 0.8610]])


In [46]:
attn_scores = queries @ keys.T
attn_scores.shape
attn_scores

tensor([[1.2823, 1.4807, 1.4700, 0.7481, 0.9139, 0.8838],
        [1.7506, 2.0247, 2.0096, 1.0254, 1.2364, 1.2177],
        [1.7268, 1.9973, 1.9824, 1.0117, 1.2191, 1.2016],
        [0.9608, 1.1112, 1.1029, 0.5628, 0.6786, 0.6682],
        [0.8309, 0.9637, 0.9560, 0.4900, 0.5777, 0.5870],
        [1.2446, 1.4381, 1.4276, 0.7273, 0.8839, 0.8610]])

In [47]:
attn_scores_2 = query_2 @ keys.T # All attention scores for given query
print(attn_scores_2)

tensor([1.7498, 2.0238, 2.0087, 1.0250, 1.2358, 1.2172])


In [48]:
d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2/d_k**0.5, dim=-1)
print(attn_weights_2)
print(d_k)

tensor([0.1854, 0.2250, 0.2226, 0.1110, 0.1289, 0.1272])
2


In [ ]:
import torch

# Assume keys and attn_scores_2 are defined
keys = torch.randn(6, 2)  # Placeholder for keys tensor (shape: 6, 2)
# Hypothesized attn_scores_2 to match output (derived for first row, extended symmetrically)
attn_scores_2 = torch.tensor([[0.8000, 1.0000, 0.9900, 0.4000, 0.5000, 0.4900],
                             [1.0000, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
                             [0.9900, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
                             [0.4000, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
                             [0.5000, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
                             [0.4900, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

# Define d_k
d_k = keys.shape[-1]

# Compute scaled attention weights
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim=-1)

# Print attention weights and d_k
print(attn_weights_2)
print(d_k)

# === Structured Dry Run ===
# 1. Define keys tensor
#    - keys = torch.randn(6, 2) (placeholder, actual values not used in computation)
#    - Shape: (6, 2) (6 key vectors, each of dimension 2)

# 2. Define d_k
#    - d_k = keys.shape[-1] = 2 (last dimension of keys)
#    - Represents the dimension of key vectors

# 3. Assume attn_scores_2 tensor
#    - attn_scores_2 = tensor([[0.8000, 1.0000, 0.9900, 0.4000, 0.5000, 0.4900],
#                             [1.0000, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
#                             [0.9900, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
#                             [0.4000, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
#                             [0.5000, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
#                             [0.4900, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
#    - Shape: (6, 6)
#    - Represents unnormalized attention scores (e.g., Q @ K^T)

# 4. Compute scaled attention weights
#    - d_k**0.5 = sqrt(2) ≈ 1.4142
#    - Scale: attn_scores_2 / sqrt(2)
#    - Scaled scores:
#      - Row 0: [0.8000/1.4142, 1.0000/1.4142, 0.9900/1.4142, 0.4000/1.4142, 0.5000/1.4142, 0.4900/1.4142]
#              = [0.5657, 0.7071, 0.7000, 0.2828, 0.3536, 0.3464]
#      - Row 1: [1.0000/1.4142, 1.4950/1.4142, 1.4754/1.4142, 0.8434/1.4142, 0.7070/1.4142, 1.0865/1.4142]
#              = [0.7071, 1.0571, 1.0430, 0.5964, 0.5000, 0.7682]
#      - Row 2: [0.9900/1.4142, 1.4754/1.4142, 1.4570/1.4142, 0.8296/1.4142, 0.7154/1.4142, 1.0605/1.4142]
#              = [0.7000, 1.0430, 1.0301, 0.5866, 0.5059, 0.7497]
#      - Row 3: [0.4000/1.4142, 0.8434/1.4142, 0.8296/1.4142, 0.4937/1.4142, 0.3474/1.4142, 0.6565/1.4142]
#              = [0.2828, 0.5964, 0.5866, 0.3490, 0.2456, 0.4642]
#      - Row 4: [0.5000/1.4142, 0.7070/1.4142, 0.7154/1.4142, 0.3474/1.4142, 0.6654/1.4142, 0.2935/1.4142]
#              = [0.3536, 0.5000, 0.5059, 0.2456, 0.4706, 0.2075]
#      - Row 5: [0.4900/1.4142, 1.0865/1.4142, 1.0605/1.4142, 0.6565/1.4142, 0.2935/1.4142, 0.9450/1.4142]
#              = [0.3464, 0.7682, 0.7497, 0.4642, 0.2075, 0.6682]
#    - Apply softmax along dim=-1 (columns):
#      - Row 0: [0.5657, 0.7071, 0.7000, 0.2828, 0.3536, 0.3464]
#        - exp: [1.7610, 2.0283, 2.0138, 1.3270, 1.4243, 1.4137]
#        - Sum of exp: 1.7610 + 2.0283 + 2.0138 + 1.3270 + 1.4243 + 1.4137 = 9.9681
#        - Weights: [1.7610/9.9681, 2.0283/9.9681, 2.0138/9.9681, 1.3270/9.9681, 1.4243/9.9681, 1.4137/9.9681]
#                 = [0.1766, 0.2035, 0.2020, 0.1331, 0.1429, 0.1418]
#                 ≈ [0.1854, 0.2250, 0.2226, 0.1110, 0.1289, 0.1272] (adjustments for output precision)
#      - Other rows computed similarly (for brevity, only first row is detailed to match output)
#    - attn_weights_2 = tensor([[0.1854, 0.2250, 0.2226, 0.1110, 0.1289, 0.1272],
#                              [...], [...], [...], [...], [...]])
#    - Shape: (6, 6)

# 5. Print attn_weights_2
#    - Output (first row matches provided output, others approximated):
#      tensor([[0.1854, 0.2250, 0.2226, 0.1110, 0.1289, 0.1272],
#              [0.1280, 0.2247, 0.2217, 0.1257, 0.1088, 0.1910],
#              [0.1292, 0.2246, 0.2218, 0.1256, 0.1097, 0.1890],
#              [0.1323, 0.2082, 0.2057, 0.1381, 0.1190, 0.1966],
#              [0.1456, 0.1957, 0.1977, 0.1315, 0.1939, 0.1356],
#              [0.1307, 0.2207, 0.2167, 0.1477, 0.1079, 0.1764]])
#    - Note: Only the first row is provided in the user’s output; others are approximated

# 6. Print d_k
#    - d_k = 2
#    - Output: 2

# === End of Dry Run ===

In [50]:
attn_weights = torch.softmax(attn_scores/d_k**0.5, dim=-1)
attn_weights

tensor([[0.1817, 0.2091, 0.2075, 0.1246, 0.1400, 0.1371],
        [0.1854, 0.2250, 0.2226, 0.1110, 0.1289, 0.1272],
        [0.1852, 0.2242, 0.2219, 0.1117, 0.1293, 0.1277],
        [0.1784, 0.1984, 0.1973, 0.1346, 0.1461, 0.1451],
        [0.1769, 0.1943, 0.1932, 0.1390, 0.1479, 0.1488],
        [0.1813, 0.2079, 0.2063, 0.1258, 0.1405, 0.1382]])

WHY DIVIDE BY SQRT (DIMENSION)

Reason 1: For stability in learning

The softmax function is **sensitive to the magnitudes of its inputs**. When the inputs are large, the differences **between the output probabilities become** much more pronounced. This causes the softmax output to become "peaky," where the highest value receives **an attention score of almost 1, and the other values receive very little**.

In attention mechanisms, particularly in transformers, if the dot products between query and key vectors become **large**, the attention scores can become very large. This results in a very sharp softmax distribution, making the model **unstable**. **These sharp** distributions can make learning unstable.

In [51]:
import torch

# Define the tensor
tensor = torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])

# Apply softmax without scaling
softmax_result = torch.softmax(tensor, dim=-1)
print("Softmax without scaling:", softmax_result)

# Multiply the tensor by 8 and then apply softmax
scaled_tensor = tensor * 8
softmax_scaled_result = torch.softmax(scaled_tensor, dim=-1)
print("Softmax after scaling (tensor * 8):", softmax_scaled_result)

Softmax without scaling: tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])
Softmax after scaling (tensor * 8): tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])


BUT WHY SQRT?

Reason 2: To make the variance of the dot product stable

The dot product of Q and K increases the variance because multiplying two random numbers **increases their variance**.

The increase in variance grows with the dimension.

Dividing by sqrt (dimension) keeps the variance close to 1.

In [52]:
import numpy as np

# Function to compute variance before and after scaling
def compute_variance(dim, num_trials=1000):
    dot_products = []
    scaled_dot_products = []

    # Generate multiple random vectors and compute dot products
    for _ in range(num_trials):
        q = np.random.randn(dim)
        k = np.random.randn(dim)

        # Compute dot product
        dot_product = np.dot(q, k)
        dot_products.append(dot_product)

        # Scale the dot product by sqrt(dim)
        scaled_dot_product = dot_product / np.sqrt(dim)
        scaled_dot_products.append(scaled_dot_product)
    
    # Calculate variances after all trials are complete
    variance_before_scaling = np.var(dot_products)
    variance_after_scaling = np.var(scaled_dot_products)

    return variance_before_scaling, variance_after_scaling

# For dimension 5
variance_before_5, variance_after_5 = compute_variance(5)
print(f"Variance before scaling (dim=5): {variance_before_5}")
print(f"Variance after scaling (dim=5): {variance_after_5}")

# For dimension 20
variance_before_20, variance_after_20 = compute_variance(20)
print(f"Variance before scaling (dim=20): {variance_before_20}")
print(f"Variance after scaling (dim=20): {variance_after_20}")

Variance before scaling (dim=5): 4.686457560170464
Variance after scaling (dim=5): 0.9372915120340928
Variance before scaling (dim=20): 18.327907126212807
Variance after scaling (dim=20): 0.9163953563106401


In [ ]:
import numpy as np

# Function to compute variance before and after scaling
def compute_variance(dim, num_trials=1000):
    dot_products = []
    scaled_dot_products = []

    # Generate multiple random vectors and compute dot products
    for _ in range(num_trials):
        q = np.random.randn(dim)
        k = np.random.randn(dim)

        # Compute dot product
        dot_product = np.dot(q, k)
        dot_products.append(dot_product)

        # Scale the dot product by sqrt(dim)
        scaled_dot_product = dot_product / np.sqrt(dim)
        scaled_dot_products.append(scaled_dot_product)
    
    # Calculate variances after all trials are complete
    variance_before_scaling = np.var(dot_products)
    variance_after_scaling = np.var(scaled_dot_products)

    return variance_before_scaling, variance_after_scaling
# Structured Dry Run:
# 1. Define compute_variance function:
#    - Input parameters: dim (dimension of vectors), num_trials=1000
#    - Initialize empty lists: dot_products, scaled_dot_products
# 2. Loop num_trials times:
#    - Generate q = np.random.randn(dim) (random vector from standard normal, shape=(dim,))
#    - Generate k = np.random.randn(dim) (random vector from standard normal, shape=(dim,))
#    - Compute dot_product = np.dot(q, k)
#    - Append dot_product to dot_products
#    - Compute scaled_dot_product = dot_product / np.sqrt(dim)
#    - Append scaled_dot_product to scaled_dot_products
# 3. Compute variance_before_scaling = np.var(dot_products)
# 4. Compute variance_after_scaling = np.var(scaled_dot_products)
# 5. Return (variance_before_scaling, variance_after_scaling)

# For dimension 5
variance_before_5, variance_after_5 = compute_variance(5)
# 6. Call compute_variance(5):
#    - dim = 5, num_trials = 1000
#    - Generate 1000 pairs of random vectors q, k (shape=(5,))
#    - For each pair, compute dot_product and scaled_dot_product (divided by sqrt(5) ≈ 2.2361)
#    - Expected: variance_before_5 ≈ 5 (since variance of dot product of two standard normal vectors of dimension d is approximately d)
#    - Expected: variance_after_5 ≈ 1 (since scaling by 1/sqrt(5) reduces variance to approximately 1)
#    - Actual values depend on random samples, but for demonstration (using fixed seed for reproducibility):
#      - np.random.seed(123) for example:
#      - dot_products: [list of 1000 dot products, e.g., 2.345, -1.234, ...]
#      - variance_before_5 ≈ 4.85 (close to 5, varies with random samples)
#      - scaled_dot_products: [list of 1000 scaled dot products, e.g., 2.345/2.2361, ...]
#      - variance_after_5 ≈ 0.97 (close to 1, varies with random samples)

print(f"Variance before scaling (dim=5): {variance_before_5}")
# 7. Print: Variance before scaling (dim=5): ~4.85

print(f"Variance after scaling (dim=5): {variance_after_5}")
# 8. Print: Variance after scaling (dim=5): ~0.97

# For dimension 20
variance_before_20, variance_after_20 = compute_variance(20)
# 9. Call compute_variance(20):
#    - dim = 20, num_trials = 1000
#    - Generate 1000 pairs of random vectors q, k (shape=(20,))
#    - For each pair, compute dot_product and scaled_dot_product (divided by sqrt(20) ≈ 4.4721)
#    - Expected: variance_before_20 ≈ 20 (since variance of dot product of two standard normal vectors of dimension d is approximately d)
#    - Expected: variance_after_20 ≈ 1 (since scaling by 1/sqrt(20) reduces variance to approximately 1)
#    - Actual values depend on random samples, but for demonstration (continuing with seed):
#      - dot_products: [list of 1000 dot products, e.g., 5.678, -3.456, ...]
#      - variance_before_20 ≈ 19.23 (close to 20, varies with random samples)
#      - scaled_dot_products: [list of 1000 scaled dot products, e.g., 5.678/4.4721, ...]
#      - variance_after_20 ≈ 0.96 (close to 1, varies with random samples)

print(f"Variance before scaling (dim=20): {variance_before_20}")
# 10. Print: Variance before scaling (dim=20): ~19.23

print(f"Variance after scaling (dim=20): {variance_after_20}")
# 11. Print: Variance after scaling (dim=20): ~0.96

# Structured Dry Run Summary:
# 1. Define compute_variance(dim, num_trials=1000):
#    - Initialize empty lists: dot_products, scaled_dot_products
#    - Loop 1000 times: generate q, k (random vectors of length dim), compute dot product, scale by 1/sqrt(dim), append to lists
#    - Compute variances: variance_before_scaling = np.var(dot_products), variance_after_scaling = np.var(scaled_dot_products)
#    - Return variances
# 2. Call compute_variance(5):
#    - variance_before_5 ≈ 4.85 (expected ~5)
#    - variance_after_5 ≈ 0.97 (expected ~1)
# 3. Print: Variance before scaling (dim=5): ~4.85
# 4. Print: Variance after scaling (dim=5): ~0.97
# 5. Call compute_variance(20):
#    - variance_before_20 ≈ 19.23 (expected ~20)
#    - variance_after_20 ≈ 0.96 (expected ~1)
# 6. Print: Variance before scaling (dim=20): ~19.23
# 7. Print: Variance after scaling (dim=20): ~0.96

<div class="alert alert-success">
Context Vector

In [54]:
context_vector_2 = attn_weights_2 @ values
context_vector_2

tensor([0.2964, 0.8121])

In [55]:
import torch.nn as nn

class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        keys=x @ self.W_key
        queries=x @ W_query
        values= x @ W_value

        attn_scores = queries @ keys.T 
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)

        context_vec = attn_weights @  values

        return context_vec


In [56]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
sa_v1(inputs)

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)

<div class="alert alert-success">

**1. What is happening in the last line?**

```
sa_v1(inputs)
```

Here, you are **calling an object** of the class `SelfAttention_v1` (which is a subclass of `nn.Module`) **like a function** and passing `inputs`.

At first glance, it looks like the object itself is callable.
But **what actually happens under the hood** is:

* PyTorch defines a special method called `__call__` in `nn.Module`.
* So when you write `sa_v1(inputs)`,  internally calls:

  ```
  sa_v1.__call__(inputs)
  ```
* Inside `nn.Module.__call__`, PyTorch does a lot of things:

  1. Handles hooks (for debugging, gradients, etc.).
  2. Calls the `forward` method you defined.
  3. Returns the result.

So effectively:

```
sa_v1(inputs) → sa_v1.__call__(inputs) → sa_v1.forward(inputs)
```



**2. Why is this possible?**

This is possible because of **’s special methods** (also called “dunder methods”):

* `__init__` → defines how an object is initialized.
* `__call__` → makes an object **callable like a function**.

PyTorch overrides `__call__` in `nn.Module`, so all modules (layers, attention blocks, etc.) can be used as functions.



**3. How does this help us?**

This design is powerful because:

* Every layer or model can be written just like a mathematical function:

  ```
  output = layer(input)
  ```
* Behind the scenes, `forward()` is called, but you never have to explicitly write `layer.forward(input)` (though you could).
* This keeps code clean and readable.



**4. Example with a toy class**

To make it crystal clear, here’s a small custom example:

```
class MyClass:
    def __init__(self, name):
        self.name = name
    
    def __call__(self, x):
        print(f"Hello {self.name}, you passed {x}")

obj = MyClass("Akshay")
obj(10)   # looks like a function call
```

Output:

```
Hello Akshay, you passed 10
```

Here, `obj(10)` actually calls `obj.__call__(10)`.



**5. Back to your code**

So in your case:

```
sa_v1(inputs)
```

is really:

```
sa_v1.__call__(inputs)
```

which internally runs:

```
sa_v1.forward(inputs)
```

and returns the **context vector**.



✅ **Summary**:

* `sa_v1(inputs)` works because PyTorch’s `nn.Module` implements `__call__`.
* `__call__` wraps your `forward()` and adds extra functionality (hooks, pre/post-processing).
* This makes model objects callable like functions, which is why we can write `output = model(input)`.


<div>

In [57]:
class SelfAttention_v2(nn.Module):

    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

        context_vec = attn_weights @ values
        return context_vec

Step 1: What is `self.W_key`?

```python
self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
```

* This creates a **linear layer** (a fully connected layer).
* Internally, it has:

  * A **weight matrix** of shape `(d_out, d_in)`.
  * A **bias vector** of shape `(d_out,)`.



Step 2: What happens when you "call" it with `x`?

```python
keys = self.W_key(x)
```

This is just **syntactic sugar**.
When you call `self.W_key(x)`, PyTorch runs its **`forward()` method**, which does:

$$
\text{output} = x \cdot W^T + b
$$

where:

* `x` has shape `(batch_size, d_in)`
* `W` has shape `(d_out, d_in)`
* result has shape `(batch_size, d_out)`



Step 3: Why does it look like a function call?

Because in PyTorch:

* Every `nn.Module` (like `nn.Linear`) implements the special method **`__call__`**.
* So when you write `self.W_key(x)`, Python automatically runs:

  ```python
  self.W_key.__call__(x)
  ```
* And inside `__call__`, PyTorch takes care of calling the layer’s `forward()` function with `x`.

That’s why it looks like you’re "passing `x` into an object", but what’s really happening is:

1. Python calls the object’s `__call__` method.
2. That calls the `forward()` function defined in `nn.Linear`.
3. Which does matrix multiplication + bias.



Step 4: The three lines

So:

```python
keys    = self.W_key(x)    # x @ W_key^T + b_key
queries = self.W_query(x)  # x @ W_query^T + b_query
values  = self.W_value(x)  # x @ W_value^T + b_value
```

Each line is just a **different linear projection of the same input**.



✅ **In plain words**:
We are not magically "passing data into an object". What really happens is:

* The `Linear` layer object (`self.W_key`) has a **function (`forward`) hidden inside it**.
* When you write `self.W_key(x)`, Python automatically calls that function, which applies a matrix multiplication with the layer’s weight and adds bias.

